[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "C1QurpV2i1aF6KrU9RNzZeyRnACowQ4jbLU3VcAjQmM3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/fme849/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
